export const TYPES = {
  // CART
  ADD_TO_CART: 'ADD_TO_CART',
  DELETE_IN_CART: 'DELETE_IN_CART',
  // AMOUNT
  INCREASE_AMOUNT: 'INCREASE_AMOUNT',
  DECREASE_AMOUNT: 'DECREASE_AMOUNT',
  MODIFY_AMOUNT: 'MODIFY_AMOUNT'
};

export const CATEGORY_FILTER = {
  ALL: 'ALL',
  FICTION: 'FICTION',
  MYSTERY: 'MYSTERY',
  HORROR: 'HORROR',
  ROMANCE: 'ROMANCE',
  'SCIFI': 'SCI-FI',
  SCIENCE: 'SCIENCE'
};